# Generated by Django 5.1.1 on 2024-10-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='First', max_length=15, unique=True),
        ),
    ]
