# Generated by Django 5.1.1 on 2024-10-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chat_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_History',
        ),
    ]
